### ISSUE TITLE
Samsung Touchwiz compatability issue

### ISSUE THREAD

**Issue by Dmole** [mclear/Android_NFC_Ring_Unlock#90]
ring will unlock ap but not lock screen... (tried 5 times)
sgs3

**Comment by JohnMcLear** [comment]
Can you provide steps to replicate this issue please?

**Comment by Dmole** [comment]
I'm not able to get it working under any condition, so the steps are:
- Download app to a Samsung Galaxy S iii running the default OS (4.3 touch wiz UI).
- Allow the app admin
- turn on nfc
- add an nfc tag
- enable the app
- lock the screen
- ring won't unlock device.

Speculation:
NFC_Ring_Control will also fail to read tags if nfc is enabled after opening the app.
maybe both apps need to wait a bit longer after nfc is enabled before trying to use it.
assuming that android turns off nfc when the device is locked and the screen is off.

**Comment by JohnMcLear** [comment]
What happens if you restart your phone with NFC enabled prior to restart?

**Comment by Dmole** [comment]
restart had no effect.

I confirmed that NFC is off when the screen is off  (I can hear the NFC ping if I put my phone on my headphone cord)

**Comment by JohnMcLear** [comment]
Well I have no idea about this, does it take a while then start working or something?  It sounds like you aren't able to use the app at all?

cc @r2DoesInc

**Comment by Dmole** [comment]
this app will not work no mater how long i wait to scan after the lock screen is shown.

This app will not scan tags on my device from the lock screen. (It will scan tags if the device is unlocked and NFC is enabled BEFORE the app is started.)

**Comment by JohnMcLear** [comment]
Well this is very bizarre..  What if you have a lock screen before you use NFC Ring Unlock such as a PIN lock screen?

**Comment by Dmole** [comment]
That is not an option in the app, my default lock screen(swipe/pin/pass) is never shown if the app is enabled. I am able to unlock the app when opening it after the device is already unlocked but that's no help.

**Comment by JohnMcLear** [comment]
Enable your default lock screen and disable "use without lock screen" and see if it works then.

The behaviour you are describing makes no sense though and it's the first time it's been reported ;\

**Comment by Dmole** [comment]
The requested settings are what I was using, are you saying it's normal to be forced to enter a password then use the ring? i was expecting it to be normal that the app replaces the login screen like other apps do.  this would not likely be reported as it is expected behavior.  The same thing happens when i turn  off my lock screen and enabling "use without lock screen" 

The app failing to work has been reported:
#2
#44 
#84

**Comment by JohnMcLear** [comment]
No it's not normal in just trying to isolate the cause of your problem.

Any chance you can post to the forum explaining it there to see if the community has any suggestions?

Cheers

J

----- Reply message -----

**Comment by r2DoesInc** [comment]
Im still completely unsure of what youre talking about, but I saw something
that threw a red flag.

The app does NOT replace your lockscreen. The standard lockscreen comes up
first, unless you use the "use with no lockscreen" that option will cause
issues if you have not disabled your stock lockscreen though.

**Comment by JohnMcLear** [comment]
Yeah I'm a terrible user. Best to post on the forum to see if others can help explain how to get setup.

**Comment by Lokki-P** [comment]
Has the unlock app been enabled correctly?
Enable/disable button will read 'enable' when app is disabled.

**Comment by r2DoesInc** [comment]
If it unlocks the app but not the phone, the issue is your tag. you either overwrote it or you have another app trying to take the scan action. scan the tag from the homsecreen.

**Comment by JohnMcLear** [comment]
Closing..  This specific issue is generally solved by scanning their tag on the homescreen and selecting the app as the default, or it can be caused by an overwrite or partial overwrite of their tag data.

**Comment by Dmole** [comment]
This is a compatibility issue with Samsung TouchWiz and is still not resolved. Not that I care because I'm using a root solution instead.

**Comment by JohnMcLear** [comment]
Closing as no longer relevant
